Add plugin - PingControl
Tolga1452/Vencord pull request #23
Opened 2024-03-23 23:15 UTC by HumanCat222

Allows you to block certain users from pinging you.
![image](https://github.com/Tolga1452/Vencord/assets/93674051/ea26e0a0-733d-4e73-ae4a-cecc7cc23b14)
![image](https://github.com/Tolga1452/Vencord/assets/93674051/77359ab9-e921-45bc-9c0c-6e6e41d4f75c)
![image](https://github.com/Tolga1452/Vencord/assets/93674051/270d6135-d597-4e46-8878-322778e7b980)
![image](https://github.com/Tolga1452/Vencord/assets/93674051/011b3b69-1481-46ee-b187-96f8972aa5c7)

2024-03-24 09:34 UTC, Trao-X commented
Why'd you have to make so many commits? 💀

2024-03-24 10:13 UTC, HumanCat222 commented
> Why'd you have to make so many commits? 💀

2 more commits

2024-03-25 13:50 UTC, Tolga1452 commented
oh my god
![image](https://github.com/Tolga1452/Vencord/assets/68483180/c52cc9c4-cbdb-4c24-a9ae-7e8014ccad3d)

2024-03-25 14:03 UTC, Tolga1452 requested changes
replacing vencord toolbox
![image](https://github.com/Tolga1452/Vencord/assets/68483180/3c415d60-dfe8-49de-90a8-9bac82ad6868)

2025-03-09 22:55 UTC, HumanCat222 commented
Discontinued, this has been replaced by the built-in ignore feature

2025-03-09 22:56 UTC, closed without merging